import {
  BarChart3,
  Binary,
  Boxes,
  Bug,
  Cloud,
  Coffee,
  Container,
  Database,
  FileCode2,
  FlaskConical,
  Infinity,
  Monitor,
  Network,
  Orbit,
  Radar,
  Route,
  ScanSearch,
  ShipWheel,
  Waypoints,
  Workflow,
  type LucideIcon,
} from "lucide-react";

const skillIconMap: Record<string, LucideIcon> = {
  "C / C++": Binary,
  Python: FileCode2,
  Java: Coffee,
  Algoritmi: Route,
  Algorithms: Route,
  "Sistemi operativi": Monitor,
  "Operating systems": Monitor,
  Concorrenza: Orbit,
  Concurrency: Orbit,
  OpenMP: Network,
  MPI: Waypoints,
  Docker: Container,
  Kubernetes: ShipWheel,
  "CI/CD": Workflow,
  "Cloud GCP e Azure": Cloud,
  "Cloud GCP and Azure": Cloud,
  gdb: Bug,
  "Analisi statica": ScanSearch,
  "Static analysis": ScanSearch,
  "Code smells": Radar,
  Testing: FlaskConical,
  "Design Patterns": Boxes,
  MySQL: Database,
  BigQuery: BarChart3,
  "Programmazione funzionale": Infinity,
  "Functional programming": Infinity,
};

export function getSkillIcon(skill: string, fallbackIcon: LucideIcon) {
  return skillIconMap[skill] ?? fallbackIcon;
}
